### ISSUE TITLE
Fred: Tasks for the 0.14.4 release 

### ISSUE THREAD

**Issue by mattsc** [mattsc/AI-demos#12]
### Main tasks for AI-demos 0.14.4
- [x] Retreating
  - [x] Add basic functionality
  - [x] Enable moving toward retreat locations farther than one move away
  - [x] Tune weighting functions
- [x] Better protect the leader at the end of the game
  - [x] Combine holding in zones and holding for leader protection
  - [x] ~~Ignore the leader when determining whether the leader hex is protected~~  -- not needed any more, this is done differently now.
  - [x] Improve rating functions
- [x] Use stronger units to hold villages
  - ~~Other improvements to defensive holding~~  -- this will take a more dedicated effort and has been postponed to a later release
- [x] Improve assigning units to zones, and moving them between zones
----
### Roadmap for upcoming releases
This is by no means an exhaustive list.  It's just a tentative collection of ideas for the main tasks for the next releases.

#### All releases
- Of course, bug fixes and taking care of newly discovered problems and issues always have the highest priority

#### 0.14.5
- Improve attack evaluation

#### 0.14.6
- Improve holding evaluation
  - Better pre-rating and combo evaluation
  - Enable multiple protect locations
  - Protect valuable units in addition to leader

#### 0.14.7
- Operations layer
  - Improve initial assessment
  - Add to / fix / improve update after moves

#### Later
- Code clean-up
- Improve evaluation speed
