### ISSUE TITLE
Fred: Tasks for the 0.14.5 release

### ISSUE THREAD

**Issue by mattsc** [mattsc/AI-demos#13]
### Main tasks for AI-demos 0.14.5

This release is dedicated to trying to improve the attack evaluation

- [x] Functional work
  - [x] Add template function for attack stats (incl. level-up hit chances)
  - [x] Attack combo evaluation: 
    - [x] Correctly account for leveling up through attack combos
    - [x] Use actual leveled-up unit information in level-up evaluation
    - [x] Correctly account for poison/slow propagation through attack combos
    - [x] Use correct unit type and stats for leveled-up defender
  - [x] get_attack_combos: use unit_hex_combos functions
  - [x] Check why att_stats sanity check fails sometimes with Knalgans
  - [x] Maybe
    - [x] Combine combo_stats into a single table
    - [x] Set counter_stats to nil when there is no counter attack
- [x] Rating adjustments:
  - [x] Correctly calculate poison/slow in attack outcomes
  - [x] Add additional information to attack outcome tables
  - [x] Don't double count poison/slow for units already poisoned/slowed
  - [x] Don't count slow as a delayed damage
  - [x] Check approximations in attack combo evaluation, improve if needed
  - [x] ~~Better evaluation of best weapon selection~~  **[postponed]**
  - [x] Add missing weapon specials to attack evaluation
  - [x] ~~Improve attack combo evaluation~~  **[postponed]**
    - [x] ~~Better pre-selection~~  **[postponed]**
    - [x] ~~More flexible method of selecting best combo~~  **[postponed]**
  - [x] Improve attack rating
    - [x] Accounting for weapon specials and traits
    - [x] Accounting for XP
    - [x] Attacks by leader when already poisoned/slowed
    - [x] Improve discouraging of undesirable attacks
    - [x] Improve derating of attacks that use too many resources for diminishing return
    - [x] Reduce trapping bonus if target has chance to die
    - [x] Limit exposing units too much through attacks
    - [x] Be more careful with high-XP units
- [x] Operations
  - [x] Use general attack_utils functions for operations ratings (partially done)
  - [x] ~~Decide up front on attackers / targets?~~  **[postponed]**
  - [x] ~~More restrictions on favorable attacks when resource starved?~~ **[not needed; at least for now]**
- [x] Execution
  - [x] Improve adjusting order of attacks
  - [x] ~~Abandon attacks that have become too dangerous~~  **[postponed]**

Not directly attack-related work:
- [x] Improve accounting for weapon specials and traits in villages and retreat actions.

----
### Roadmap for upcoming releases
This is by no means an exhaustive list.  It's just a tentative collection of ideas for the main tasks for the next releases.

#### All releases
- Of course, bug fixes and taking care of newly discovered problems and issues always have the highest priority

#### 0.14.6
- Improve holding evaluation
  - Better pre-rating and combo evaluation
  - Enable multiple protect locations
  - Protect valuable units in addition to leader

#### 0.14.7
- Operations layer
  - Improve initial assessment
  - Add to / fix / improve update after moves

#### Later
- Code clean-up
- Improve evaluation speed
