### ISSUE TITLE
Fred: Tasks for the 0.14.6 release

### ISSUE THREAD

**Issue by mattsc** [mattsc/AI-demos#14]
### Main tasks for AI-demos 0.14.6

This release is dedicated to improving the holding, advancing, retreating and village actions

- [x] Holding
  - [x] Improve the pre-rating
  - [x] Improvements to what constitutes a "good combo"
  - [x] Improve which units are used for holding
  - [x] Do not hold if not necessary
  - [x] ~Enable multiple protect locations~  **postponed**
    - [x] ~Actively protect valuable units~
  - [x] More careful with high-XP units
  - [x] Discourage holding with single units
- [x] Advancing
  - [x] More accurate threat assessment
  - [x] More careful with high-XP units
  - [x] Don't move leader off keep for advancers
  - [x] Don't necessarily move trapped units
  - [x] If no advance/retreat possible, do "desperate attack"
- [x] Retreating
  - [x] Stronger emphasis on good terrain if no safe location can be found
  - [x] Coordinate multiple unit retreats
  - [x] ~Actively block enemies from retreating units?~  **postponed**
- [x] ~Village grabbing~  **postponed**
  - [x] ~Improve assessment of threats~
- [x] ~Operations layer~  **postponed**
  - [x] ~Are enemies assigned to zones correctly?~
  - [x] ~Hold back on certain actions (e.g. move leader to village) until holding is done~
  - [x] ~If other units are holding already, do not move past them~
  - [x] ~If other units have attacked, try to stay close to them~
  - [x] ~Don't advance individual units too far~
----
### Roadmap for upcoming releases
This is by no means an exhaustive list.  It's just a tentative collection of ideas for the main tasks for the next releases.

#### All releases
- Of course, bug fixes and taking care of newly discovered problems and issues always have the highest priority

#### 0.14.7
- Improvements to the operations layer

#### 0.14.8
- Code clean-up resulting in:
- Enable Fred to
  - play Side 2
  - play other factions

#### Later
- Later releases might focus on any of the following
  - Enable Fred to play other maps
  - Further improvements to attacks, holding, advancing and/or retreating
  - Internal clean-up of code and evaluation speed-up
    - Use external candidate actions
