### ISSUE TITLE
Fred: Tasks for upcoming releases

### ISSUE THREAD

**Issue by mattsc** [mattsc/AI-demos#15]
### Main upcoming tasks for AI-demos

- [ ] Overall operations assessment
  - [x] Reduce Fred's exaggerated defensiveness
    - [x] Increase overall aggressiveness
    - [x] Improve accounting for time-of-day related changes
      - [x] Operations layer assessment
      - [x] Apply in tactics layer evaluations
    - [x] How do we deal with chaotic enemy factions?
  - [ ] Make more decisions up front
    - [x] Overall behavior for the turn
    - [x] Where to set up the fronts
    - [ ] Which parts of the map are too dangerous to move into
    - [x] Which units to use for what
    - [ ] More?
  - [x] Do we want different behavior by zone?
  - [ ] Overall direction of movement
    - [ ] E.g. if enemy leader does not stay on keep
- [ ] Mid-turn operations updates
  - [ ] Clean up how this is done
  - [ ] Add updates for
    - [ ] protect_locs
    - [ ] Retreaters
    - [ ] Leader threats
    - [ ] What else?
  - [ ] Set a flag at execution that triggers certain re-evaluations?
- [ ] Village grabbing operations assessment
  - [ ] Don’t grab villages too far forward if unit can be trapped
  - [x] Don’t always execute grab right away
  - [ ] Decide if grabbing new villages or holding current ones is more important
- [x] Advancing operations assessment
  - [x] More aggressive advancing when winning
- [ ] Holding operations assessment
  - [ ] Better assessment of hold utility
  - [x] Prefer holds close to (and do not go past)
    - [x] Units which have already moved
    - [ ] Impassable hexes
  - [x] Improve restrictions on holds with single units
- [x] Retreating operations assessment
  - [x] Improve adjusting direction of retreat based on overall situation
  - [x] Use safest village, not closest village for leader retreats
- [ ] Attacking operations assessment
  - [ ] Don’t use too many resources on individual attack
    - [ ] in particular on leader threats
  - [ ] More restrictions on favorable attacks when resource starved
  - [x] Delay enemy leader kill to get most XP
- [x] Leader action operations assessment
  - [x] Ensure leader retreats when poisoned and/or slowed
- [x] Pre-recruit operations assessment
  - [x] Better assessment of which hexes to recruit on
- [ ] Move execution
  - [ ] Move out of way
    - [ ] Improve direction of MOOW
    - [ ] Do not move into final position if not necessary
  - [ ] Attacks
    - [ ] Don’t leave units exposed if not all units needed
    - [ ] Improve conditions when to abandon attacks
- [ ] Functionality
  - [x] Hold back on pre-determined actions
    - [x] but treat them as if they had been executed
  - [ ] Clean up which type of power/value/etc. parameters to use in each situation
  - [x] When does time-of-day need to be considered?
    - [x] Prepare for Fred playing Side 2
  - [x] More consistent use of value_ratio and similar parameters
  - [ ] Correctly take specials into account for hit_chance
----
### Roadmap for upcoming releases
This is by no means an exhaustive list.  It's just a tentative collection of ideas for the main tasks for the next releases.

#### All releases
- Of course, bug fixes and taking care of newly discovered problems and issues always have the highest priority

#### Later releases might focus on any of the following
- Code clean-up:
  - Pull out hard-coded parameters
  - Enable Fred to play other maps
  - Further improvements to attacks, holding, advancing and/or retreating
  - Internal clean-up of code and evaluation speed-up
